import {Food} from './app/shared/models/food'
import { Tag } from './app/shared/tag'

export const sample_foods:Food[]=[
    {
        id:'1',
        name: 'Traditional SLAMBUC',
        cookTime: '60-70',
        price: 7.5,
        favorite: false,
        origins: ['Hungary'],
        stars: 4.5,
        imageUrl: 'assets/slambuc.jpg',
        tags: ['Hungarian', 'Lunch'],
      },
      {
        id:'2',
        name: 'Bácskai Rice with Meat',
        cookTime: '75-80',
        price: 6.0,
        favorite: false,
        origins: ['Hungary', 'Bácska'],
        stars: 4.7,
        imageUrl: 'assets/bacskai_rizses_hus.jpg',
        tags: ['Hungarian', 'Lunch', 'Meat'],
      },
      {
        id:'3',
        name: 'Ratatouille a la Hungary',
        price: 3.0,
        cookTime: '30-35',
        favorite: true,
        origins: ['Hungary'],
        stars: 5.0,
        imageUrl: 'assets/lecso.jpg',
        tags: ['FastFood', 'Hungarian'],
      },
      {
        id:'4',
        name: 'Hungarian pizza',
        price: 10.0,
        cookTime: '60-65',
        favorite: true,
        origins: ['Hungary'],
        stars: 4.3,
        imageUrl: 'assets/magyaros_pizza.jpg',
        tags: ['Lunch', 'Hungarian','Pizza','Cheesy'],
      },
      {
        id:'5',
        name: 'Langos',
        price: 2.5,
        cookTime: '120',
        favorite: false,
        origins: ['Hungary'],
        stars: 4.0,
        imageUrl: 'assets/langos.jpg',
        tags: ['Hungarian', 'Cheesy','Yummy'],
      },
      {
        id:'6',
        name: 'Chicken paprikash with noodles',
        price: 8.0,
        cookTime: '65-70',
        favorite: false,
        origins: ['Hungary'],
        stars: 4.7,
        imageUrl: 'assets/paprikas_csirke.jpg',
        tags: ['Lunch', 'Yummy', 'Meat','Hungarian'],
      },
    ]
    
    export const sample_tags:Tag[] = [
      { name: 'All', count: 6 },
      { name: 'Hungarian', count: 6 },
      { name: 'Pizza', count: 1 },
      { name: 'Lunch', count: 4 },
      { name: 'FastFood', count: 1 },
      { name: 'Meat', count: 2 },
      { name: 'Yummy', count: 2 },
      { name: 'Cheesy', count: 2 },
    ]
